### ISSUE TITLE
How to get the real sales data of an product item

### ISSUE THREAD

**Issue by kalidio** [XavierZambrano/mercadolibre-scraper#1]
Now the sales display is an approximate data, for example 500+, how to get the real sales data of the product? any good ideas? thanks!

**Comment by XavierZambrano** [comment]
I believe you can't get the exact "sold_stock"/sales of a product, only an "approximation."

If you know of another repository or app that extracts the exact sales of a product, please share the link, and I will gladly check it out.

**Comment by kalidio** [comment]
yes, it's more difficult to solve such problems. thanks.
